# Generated by Django 5.2.17 on 2026-09-30 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('work_logs', '0001_initial'),
        ('work_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='log_type',
            field=models.CharField(choices=[('NOTE', 'Note'), ('STARTED', 'Started'), ('PROGRESS', 'Progress'), ('ISSUE', 'Issue'), ('COMPLETED', 'Completed')], default='NOTE', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('BEFORE', 'Before'), ('DURING', 'During'), ('AFTER', 'After'), ('DOCUMENT', 'Document')], default='DURING', max_length=20)),
                ('file', models.FileField(upload_to='work_evidence/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_evidence', to='companies.company')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_evidence', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='work_orders.workorder')),
            ],
        ),
    ]
