# Generated by Django 5.2.17 on 2026-09-30 14:31

import work_logs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_logs', '0002_worklog_log_type_workevidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workevidence',
            name='file',
            field=models.FileField(upload_to='work_evidence/', validators=[work_logs.validators.validate_evidence_file]),
        ),
    ]
