# Generated by Django 5.2.17 on 2026-10-05 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_phone_verified_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('code_hash', models.CharField(max_length=128)),
                ('purpose', models.CharField(choices=[('PHONE_VERIFICATION', 'Phone Verification'), ('PASSWORD_RESET', 'Password Reset'), ('PHONE_CHANGE', 'Phone Change')], max_length=30)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_otps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
