# Generated by Django 5.2.17 on 2026-10-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_phoneotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('FOUNDER', 'Founder'), ('ADMIN', 'Admin'), ('WORKER', 'Worker'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=20),
        ),
    ]
