# Generated by Django 5.2.17 on 2026-10-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_role'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('companies', '0003_platformsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='phone_group',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(role__in=['FOUNDER', 'ADMIN', 'WORKER'], then=models.Value('STAFF')), default=models.Value('CUSTOMER')), output_field=models.CharField(max_length=8)),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('phone_group', 'phone'), name='unique_phone_within_role_group'),
        ),
    ]
