# Generated by Django 5.2.17 on 2026-10-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_status_company_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='SEIYALAM', max_length=200)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=20)),
                ('support_website', models.URLField(blank=True)),
                ('default_currency', models.CharField(default='INR', max_length=10)),
                ('default_timezone', models.CharField(default='Asia/Kolkata', max_length=100)),
                ('default_language', models.CharField(default='en', max_length=20)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True, default='SEIYALAM is currently under maintenance. Please try again later.')),
                ('allow_customer_registration', models.BooleanField(default=True)),
                ('allow_customer_otp_login', models.BooleanField(default=True)),
                ('max_upload_size_mb', models.PositiveIntegerField(default=10)),
                ('platform_announcement', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
